.\protoc.exe --proto_path=src --csharp_out=gen graph.proto
.\protoc.exe --proto_path=src --csharp_out=gen attr_value.proto
.\protoc.exe --proto_path=src --csharp_out=gen function.proto
.\protoc.exe --proto_path=src --csharp_out=gen graph.proto
.\protoc.exe --proto_path=src --csharp_out=gen list.txt
.\protoc.exe --proto_path=src --csharp_out=gen node_def.proto
.\protoc.exe --proto_path=src --csharp_out=gen op_def.proto
.\protoc.exe --proto_path=src --csharp_out=gen resource_handle.proto
.\protoc.exe --proto_path=src --csharp_out=gen tensor.proto
.\protoc.exe --proto_path=src --csharp_out=gen tensor_shape.proto
.\protoc.exe --proto_path=src --csharp_out=gen types.proto
.\protoc.exe --proto_path=src --csharp_out=gen versions.proto